import { lazy } from 'react';

export const toolComponents: Record<string, React.LazyExoticComponent<any>> = {
	timestamp: lazy(() => import('../../tools/developer/timestamp/component')),
	uuid: lazy(() => import('../../tools/developer/uuid/component')),
	hash: lazy(() => import('../../tools/developer/hash/component')),
	binary: lazy(() => import('../../tools/developer/binary/component')),
	checksum: lazy(() => import('../../tools/developer/checksum/component')),
	color: lazy(() => import('../../tools/text/color/component')),
	url: lazy(() => import('../../tools/encoding/url/component')),
	regex: lazy(() => import('../../tools/text/regex/component')),
	diff: lazy(() => import('../../tools/text/diff/component')),
	markdown: lazy(() => import('../../tools/text/markdown/component')),
	case: lazy(() => import('../../tools/text/case/component')),
	csv: lazy(() => import('../../tools/format/csv/component')),
	yaml: lazy(() => import('../../tools/format/yaml/component')),
	'css-minify': lazy(() => import('../../tools/css/minify/component')),
	json: lazy(() => import('../../tools/json/format/component')),
	jwt: lazy(() => import('../../tools/crypto/jwt/component')),
	base64: lazy(() => import('../../tools/encoding/base64/component')),
	'html-entity': lazy(() => import('../../tools/encoding/html-entity/component')),
	'js-escape': lazy(() => import('../../tools/encoding/js-escape/component')),
	cron: lazy(() => import('../../tools/developer/cron/component')),
	password: lazy(() => import('../../tools/crypto/password/component')),
	'css-unit': lazy(() => import('../../tools/css/unit-converter/component')),
	'word-count': lazy(() => import('../../tools/text/word-count/component')),
	nanoid: lazy(() => import('../../tools/developer/nanoid/component')),
	jsonpath: lazy(() => import('../../tools/json/jsonpath/component')),
	xml: lazy(() => import('../../tools/format/xml/component')),
	lorem: lazy(() => import('../../tools/text/lorem/component')),
	'html-format': lazy(() => import('../../tools/format/html/component')),
};
